package com.abhiditya.urlshortener;

import com.abhiditya.urlshortener.model.Url;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class UrlTest {
    
    @Test
    public void testUrlModel() {
        Url url = new Url();
        url.setId(1L);
        url.setOriginalUrl("https://example.com");
        url.setShortUrl("http://localhost:8080/abc");
        url.setClickCount(5);
        url.setCreatedAt(123456789L);
        
        assertEquals(1L, url.getId());
        assertEquals("https://example.com", url.getOriginalUrl());
        assertEquals("http://localhost:8080/abc", url.getShortUrl());
        assertEquals(5, url.getClickCount());
        assertEquals(123456789L, url.getCreatedAt());
        
        // Test toString, equals, hashCode generated by Lombok
        assertNotNull(url.toString());
        assertTrue(url.equals(url));
        assertEquals(url.hashCode(), url.hashCode());
    }
}
